version: '2'
services:
  loadbalancer:
    image: 'dockercloud/haproxy:latest'
    environment:
      CERT_FOLDER: /certs/
    links:
      - interfaceserver
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./certs/:/certs/
    ports:
      - 443:443
      - 80:80
  scheduler:
    image: divvycloud/botfactory
    env_file:
      - register.env
    environment:
      VIRTUAL_ENV: /
      COMPANY_NAME: ${COMPANY_NAME}
      CONTACT_NAME: ${CONTACT_NAME}
      CONTACT_EMAIL: ${CONTACT_EMAIL}
    entrypoint:
    - /entrypoint.sh
    links:
    - elasticsearch:elasticsearch
    - redis:redis
    - mysql:mysql
    command:
    - divvycloudjobscheduler
    - -n

  interfaceserver:
    image: divvycloud/botfactory
    environment:
      VIRTUAL_ENV: /
      VIRTUAL_HOST: "http://*, https://*"
    entrypoint:
    - /entrypoint.sh
    links:
    - elasticsearch:elasticsearch
    - redis:redis
    - mysql:mysql
    ports:
    - 8001:8001/tcp
    command:
    - ./uwsgi.sh

  Worker:
    image: divvycloud/botfactory
    environment:
      VIRTUAL_ENV: /
    entrypoint:
    - /entrypoint.sh
    links:
    - elasticsearch:elasticsearch
    - redis:redis
    - mysql:mysql
    command:
    - divvycloudworker
    - -t
    - on-demand,harvester,processor
    - -n

  longharvest:
    image: divvycloud/botfactory
    environment:
      VIRTUAL_ENV: /
    entrypoint:
    - /entrypoint.sh
    links:
    - elasticsearch:elasticsearch
    - redis:redis
    - mysql:mysql
    command:
    - divvycloudworker
    - -t
    - harvester-long
    - -n

  mysql-setup:
    image: divvycloud/botfactory-db-setup
    environment:
      MYSQL_PASSWORD: divvy
      MYSQL_ROOT_PASSWORD: divvy
      MYSQL_USER: divvy
    stdin_open: true
    tty: true

  mysql:
    image: mysql
    ports:
      - 3306/tcp
    volumes:
      - ./data/db:/var/lib/mysql 
    volumes_from:
      - mysql-setup
    environment:
      MYSQL_ROOT_PASSWORD: divvy
      MYSQL_DATABASE: divvy
      MYSQL_USER: divvy
      MYSQL_PASSWORD: divvy


  redis:
    image: redis
    ports:
    - 6379/tcp

  elasticsearch:
    image: elasticsearch:1.7
    volumes:
      - ./data/esdata:/usr/share/elasticsearch/data
    ports:
    - 9200/tcp
    command:
    - elasticsearch
    - -Des.cluster.name=divvy
