version: '2'
services:
  scheduler:
    image: divvycloud/quickstart
    environment:
      VIRTUAL_ENV: /
      COMPANY_NAME: ${COMPANY_NAME}
      CONTACT_NAME: ${CONTACT_NAME}
      CONTACT_EMAIL: ${CONTACT_EMAIL}
    entrypoint:
    - /entrypoint.sh
    links:
    - elasticsearch:elasticsearch
    - redis:redis
    - mysql:mysql
    - mysql_secure:mysql_secure
    command:
    - divvycloudjobscheduler
    - -n

  interfaceserver:
    image: divvycloud/quickstart
    environment:
      VIRTUAL_ENV: /
    entrypoint:
    - /entrypoint.sh
    links:
    - elasticsearch:elasticsearch
    - redis:redis
    - mysql:mysql
    - mysql_secure:mysql_secure
    ports:
    - 8001:8001/tcp
    command:
    - ./uwsgi.sh

  Worker:
    image: divvycloud/quickstart
    environment:
      VIRTUAL_ENV: /
    entrypoint:
    - /entrypoint.sh
    links:
    - elasticsearch:elasticsearch
    - redis:redis
    - mysql:mysql
    - mysql_secure:mysql_secure
    command:
    - divvycloudworker
    - -t
    - on-demand,harvester,processor
    - -n

  longharvest:
    image: divvycloud/quickstart
    environment:
      VIRTUAL_ENV: /
    entrypoint:
    - /entrypoint.sh
    links:
    - elasticsearch:elasticsearch
    - redis:redis
    - mysql:mysql
    - mysql_secure:mysql_secure
    command:
    - divvycloudworker
    - -t
    - harvester-long
    - -n

  mysql:
    image: mysql
    ports:
      - 3306/tcp
    volumes:
      - ./db:/var/lib/mysql 
    environment:
      MYSQL_ROOT_PASSWORD: divvy
      MYSQL_DATABASE: divvy
      MYSQL_USER: divvy
      MYSQL_PASSWORD: divvy

  mysql_secure:
    image: mysql
    ports:
      - 3306/tcp
    volumes:
      - ./secure_db:/var/lib/mysql 
    environment:
      MYSQL_ROOT_PASSWORD: divvy
      MYSQL_DATABASE: divvykeys
      MYSQL_USER: divvy
      MYSQL_PASSWORD: divvy

  redis:
    image: redis
    ports:
    - 6379/tcp

  elasticsearch:
    image: elasticsearch:1.7
    volumes:
      - ./esdata:/usr/share/elasticsearch/data
    ports:
    - 9200/tcp
    command:
    - elasticsearch
    - -Des.cluster.name=divvy
